name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          debug: true
          script: |
            echo "=== Starting deployment process ==="

            # Vérifier le répertoire
            if [ ! -d "/home/notia/Notia" ]; then
              echo "Directory does not exist, creating..."
              mkdir -p /home/notia/Notia
              cd /home/notia/Notia
              git clone https://github.com/CreniautB/notia.git .
            else
              echo "Directory exists, proceeding with update..."
              cd /home/notia/Notia
            fi

            # Afficher la branche actuelle et le dernier commit
            echo "=== Current branch and commit ==="
            git branch
            git log -1

            # Forcer la mise à jour du code (au lieu de git pull)
            echo "=== Forcing update to latest changes ==="
            git fetch origin
            git stash || true
            git reset --hard origin/master
            git clean -fd package-lock.json || true
            echo "Local changes discarded and reset to remote master completed"

            # Installer les dépendances
            echo "=== Installing dependencies ==="
            npm install || { echo "npm install failed"; exit 1; }

            # Créer le fichier .env pour le backend
            echo "=== Création du fichier .env pour le backend ==="
            cat > apps/backend/.env << 'EOL'
            # Configuration de la base de données
            MONGODB_URI=${{ secrets.MONGODB_URI }}

            # Options avancées pour MongoDB
            MONGODB_RETRY_ATTEMPTS=3
            MONGODB_RETRY_DELAY=1000
            MONGODB_CONNECTION_TIMEOUT=10000

            # Port de l'application
            PORT=${{ secrets.PORT }}

            # Configuration de l'authentification Google OAuth
            GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
            GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
            GOOGLE_CALLBACK_URL=${{ secrets.GOOGLE_CALLBACK_URL }}

            # Liste des emails autorisés comme administrateurs
            ADMIN_EMAILS=${{ secrets.ADMIN_EMAILS }}

            # Secret pour les sessions
            SESSION_SECRET=${{ secrets.SESSION_SECRET }}

            # URL du frontend pour les redirections
            FRONTEND_URL=${{ secrets.FRONTEND_URL }}

            # Autres variables d'environnement
            NODE_ENV=${{ secrets.NODE_ENV }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            EOL

            # Vérifier que MONGODB_URI n'est pas vide
            if [ -z "$(grep -oP '(?<=MONGODB_URI=).*' apps/backend/.env)" ]; then
              echo "❌ Erreur: MONGODB_URI est vide dans le fichier .env du backend"
              echo "Veuillez configurer le secret MONGODB_URI dans les paramètres GitHub Actions."
              exit 1
            fi

            # Créer le fichier .env pour le frontend
            echo "=== Création du fichier .env pour le frontend ==="
            cat > apps/frontend/.env.local << 'EOL'
            # URL de l'API backend
            NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
            EOL

            # Vérifier que NEXT_PUBLIC_API_URL n'est pas vide
            if [ -z "$(grep -oP '(?<=NEXT_PUBLIC_API_URL=).*' apps/frontend/.env.local)" ]; then
              echo "❌ Erreur: NEXT_PUBLIC_API_URL est vide dans le fichier .env.local du frontend"
              echo "Veuillez configurer le secret NEXT_PUBLIC_API_URL dans les paramètres GitHub Actions."
              echo "Ce secret doit contenir l'URL complète de l'API, par exemple: https://notia-api.example.com"
              exit 1
            fi

            # Vérifier la connexion à MongoDB avant de continuer
            echo "=== Vérification de la connexion à MongoDB ==="
            # Installer mongodb-clients si nécessaire
            which mongosh > /dev/null || sudo apt-get update && sudo apt-get install -y mongodb-clients

            # Extraire l'URI de MongoDB du fichier .env
            MONGO_URI=$(grep MONGODB_URI apps/backend/.env | cut -d '=' -f2)

            # Afficher l'URI (en masquant les informations sensibles)
            MASKED_URI=$(echo "$MONGO_URI" | sed 's/\/\/.*@/\/\/****:****@/')
            echo "URI MongoDB: $MASKED_URI"

            # Vérifier si l'URI est valide et contient tous les éléments nécessaires
            if [[ ! "$MONGO_URI" =~ ^mongodb(\+srv)?:\/\/ ]]; then
              echo "❌ Erreur: Format de l'URI MongoDB invalide"
              echo "L'URI doit commencer par mongodb:// ou mongodb+srv://"
              exit 1
            fi

            # Tester la connexion à MongoDB avec plus de détails
            echo "Tentative de connexion à MongoDB..."
            if mongosh "$MONGO_URI" --eval "try { db.adminCommand('ping'); print('Databases:'); db.getMongo().getDBNames().forEach(db => print(' - ' + db)); } catch(e) { print('Error: ' + e); quit(1); }" > mongo_test_output.txt 2>&1; then
              echo "✅ Connexion à MongoDB réussie !"
              cat mongo_test_output.txt
            else
              echo "❌ Erreur: Impossible de se connecter à MongoDB"
              echo "Détails de l'erreur:"
              cat mongo_test_output.txt
              echo "Vérifiez l'URI de connexion et assurez-vous que MongoDB est accessible."
              exit 1
            fi

            # Vérifier si la base de données "notia" existe, sinon la créer avec des données de test
            echo "Vérification de la base de données notia..."
            if ! grep -q "notia" mongo_test_output.txt; then
              echo "⚠️ La base de données 'notia' n'existe pas encore, initialisation avec des données de test..."
              mongosh "$MONGO_URI" --eval '
                use notia;
                // Créer une collection quiz avec quelques entrées de test
                db.quizzes.insertMany([
                  {
                    title: "Quiz de démarrage",
                    description: "Quiz de test pour vérifier que tout fonctionne",
                    theme: "science",
                    difficulty: "easy",
                    questions: [
                      {
                        type: "multiple_choice",
                        content: "Quelle est la capitale de la France?",
                        options: [
                          { content: "Berlin", isCorrect: false },
                          { content: "Paris", isCorrect: true },
                          { content: "Rome", isCorrect: false },
                          { content: "Madrid", isCorrect: false }
                        ],
                        points: 10
                      }
                    ],
                    createdAt: new Date(),
                    updatedAt: new Date()
                  }
                ]);
                print("Base de données initialisée avec succès!");
              ' || { echo "Erreur lors de l'initialisation de la base de données"; exit 1; }
            fi

            # Nettoyage du fichier temporaire
            rm mongo_test_output.txt

            # Build
            echo "=== Building projects ==="
            npx nx run-many --target=build --projects=frontend,backend || { echo "Build failed"; exit 1; }

            # Vérifier les processus PM2
            echo "=== Current PM2 processes ==="
            pm2 list

            # Redémarrer les services
            echo "=== Restarting services ==="

            # Supprimer les processus arrêtés avant d'en créer de nouveaux
            echo "Nettoyage des processus PM2 arrêtés..."
            pm2 delete notia-frontend 2>/dev/null || true
            pm2 delete notia-backend 2>/dev/null || true

            # Démarrage des services
            echo "Démarrage des services..."
            cd /home/notia/Notia

            # Vérifier si le fichier server.js existe
            if [ -f "apps/frontend/.next/standalone/server.js" ]; then
              echo "Démarrage du frontend..."
              PORT=3000 NODE_ENV=production pm2 start apps/frontend/.next/standalone/server.js --name notia-frontend || { echo "PM2 start frontend failed"; exit 1; }
            else
              echo "❌ Erreur: Le fichier server.js du frontend n'existe pas à l'emplacement attendu."
              ls -la apps/frontend/.next/
            fi

            if [ -f "apps/backend/dist/main.js" ]; then
              echo "Démarrage du backend..."
              pm2 start apps/backend/dist/main.js --name notia-backend || { echo "PM2 start backend failed"; exit 1; }
            else
              echo "❌ Erreur: Le fichier main.js du backend n'existe pas à l'emplacement attendu."
              ls -la apps/backend/dist/
            fi

            # Sauvegarder la configuration PM2
            pm2 save

            echo "=== Deployment complete ==="
